services:
  mcxboxbroadcast:
    container_name: mcxboxbroadcast-standalone
    build:
      context: .
      dockerfile: ./bootstrap/standalone/Dockerfile
    restart: unless-stopped
    volumes:
      - ./config:/opt/app/config
    develop:
      watch:
        # Watch source code changes
        - action: rebuild
          path: ./core/src/
        - action: rebuild
          path: ./bootstrap/standalone/src/

        # Watch build configuration changes
        - action: rebuild
          path: ./build.gradle.kts
        - action: rebuild
          path: ./bootstrap/standalone/build.gradle.kts
        - action: rebuild
          path: ./settings.gradle.kts
        - action: rebuild
          path: ./gradle.properties
        - action: rebuild
          path: ./build-logic/
